require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNDemo' do
  # Pods for RNDemo
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Masonry'

  target 'RNDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end

  target 'RNDemoUITests' do
    # Pods for testing
  end

end
